# Generated by Django 3.2.3 on 2021-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210701_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='background',
            field=models.FileField(default='main/static/img/svg/back_img_profil.svg', upload_to='main/static/media/avatars/'),
        ),
    ]
