# Generated by Django 3.2.3 on 2021-07-02 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 15, 41, 22, 511606)),
        ),
    ]
