# Generated by Django 3.1.6 on 2021-07-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_profile_procent'),
        ('main', '0004_auto_20210709_2142'),
    ]

    operations = [
    ]
