# Generated by Django 3.1.6 on 2021-07-12 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_merge_20210712_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='back_photo',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='background',
            field=models.FileField(default='main/static/img/svg/back_img_profil.svg', upload_to='main/static/media/avatars/'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.FileField(default='main/static/img/svg/user_logo.svg', upload_to='main/static/media/avatars/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='token_cost',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
