# Generated by Django 3.2.3 on 2021-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210720_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isReaded',
            field=models.BooleanField(default=False),
        ),
    ]
